version: '3.3'
services:
  invaps:
    image: ghcr.io/geschke/invaps:main
    container_name: invaps
    restart: always
    ports:
      - "8080:8080"
    #volumes:
      #- type: bind
      #  source: ./config
      #  target: /config
      #- type: bind
      #  source: ../.env.test
      #  target: /config/.env
      
    environment:
      GIN_MODE: release
      #DBHOST: <database host>
      #DBUSER: solardbuser
      #DBNAME: solardb
      #DBPASSWORD: <database password>
      #DBPORT: 3307

